# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NasaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NasaApp
	pod 'Alamofire'
	pod 'Kingfisher', '~> 7.0'
	pod 'SkeletonView'

  target 'NasaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NasaAppUITests' do
    # Pods for testing
  end

end
